### ISSUE TITLE
Script to create .md from spreadsheet

### ISSUE THREAD

**Issue by pathumego** [CodeLanka/sinhala-web#11]
@pasindud Can you please revise the script to make `.md` files and make them go directly into `_posts` folder

**Comment by pasindud** [comment]
https://github.com/CodeLanka/sinhala-web/commit/14dc72ccfb1caa24a2c076004d6d69a9837f6041 :+1: 
have a check probably there are some problems

**Comment by pasindud** [comment]
@pathumego bump

**Comment by pathumego** [comment]
:+1:
